import type { Metadata } from "next";
import { ReactNode } from "react";
import "../../../styles/index.css";
import Pwa from "./Pwa";
import HeaderContainer from "../shared/Header";
import { Layout } from "antd";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function PublicLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="en">
            <body>
                <Pwa>
                    <Layout>
                        <HeaderContainer />
                        {children}
                    </Layout>
                </Pwa>
            </body>
        </html>
    );
}